name: Bump Version

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_GITHUB_PAT }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bump version
        run: node ./scripts/bump-version.js

      - name: Commit and Push Version Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION 

          # Check for changes
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

          NEW_VERSION=$(cat VERSION)
          git commit -m "chore: auto-bump version to $NEW_VERSION"
          git push

          git tag "v$NEW_VERSION"
          git push --tags

