name: Create a release and bump release version

on:
  workflow_dispatch:

jobs:
  bump_release_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_GITHUB_PAT }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Bump release version
        run: node ./scripts/bump-release-version.js

      - name: Commit and Push Version Update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION 
          NEW_VERSION=$(cat VERSION)
          git commit -m "chore: auto-bump release version to $NEW_VERSION"
          git push

      - name: Create Git Tag
        run: |
          NEW_VERSION=$(cat VERSION)
          git tag "v$NEW_VERSION"
          git push --tags

      - name: Merge develop into main
        run: |
          git fetch origin main:main
          git checkout main
          git merge --no-ff --no-edit develop
          git push origin main
