name: Verify PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  verify_pr_title:
    runs-on: ubuntu-latest

    steps:
      - name: PR Title Checker
        uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_PAT }}
          configuration_path: .github/pr-title-checker-config.json #(optional. defaults to .github/pr-title-checker-config.json)
